<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <NeutralLanguage>en-US</NeutralLanguage>
        <AssemblyName>Overlayer.Module.ADOFAI</AssemblyName>
        <LangVersion>latest</LangVersion>
        <OverlayerPath Condition="'$(OverlayerPath)' == ''">../../Overlayer/Overlayer</OverlayerPath>
    </PropertyGroup>
	
    <ItemGroup>
		<Reference Include="Overlayer" HintPath="$(OverlayerPath)/bin/Release_ML/netstandard2.1/Overlayer.dll" />
        <Reference Include="0Harmony" HintPath="$(GamePath)/MelonLoader/net35/0Harmony.dll" />
        <Reference Include="Accessibility" HintPath="$(GamePath)/$(GameData)/Managed/Accessibility.dll" />
        <Reference Include="Assembly-CSharp-firstpass" HintPath="$(GamePath)/$(GameData)/Managed/Assembly-CSharp-firstpass.dll" />
        <Reference Include="Assembly-CSharp" HintPath="$(GamePath)/$(GameData)/Managed/Assembly-CSharp.dll" />
        <Reference Include="com.rlabrecque.steamworks.net" HintPath="$(GamePath)/$(GameData)/Managed/com.rlabrecque.steamworks.net.dll" />
        <Reference Include="DemiLib" HintPath="$(GamePath)/$(GameData)/Managed/DemiLib.dll" />
        <Reference Include="DOTween" HintPath="$(GamePath)/$(GameData)/Managed/DOTween.dll" />
        <Reference Include="DOTweenPro" HintPath="$(GamePath)/$(GameData)/Managed/DOTweenPro.dll" />
        <Reference Include="I18N.CJK" HintPath="$(GamePath)/$(GameData)/Managed/I18N.CJK.dll" />
        <Reference Include="I18N" HintPath="$(GamePath)/$(GameData)/Managed/I18N.dll" />
        <Reference Include="I18N.MidEast" HintPath="$(GamePath)/$(GameData)/Managed/I18N.MidEast.dll" />
        <Reference Include="I18N.Other" HintPath="$(GamePath)/$(GameData)/Managed/I18N.Other.dll" />
        <Reference Include="I18N.Rare" HintPath="$(GamePath)/$(GameData)/Managed/I18N.Rare.dll" />
        <Reference Include="I18N.West" HintPath="$(GamePath)/$(GameData)/Managed/I18N.West.dll" />
        <Reference Include="Mono.Data.Sqlite" HintPath="$(GamePath)/$(GameData)/Managed/Mono.Data.Sqlite.dll" />
        <Reference Include="Mono.Posix" HintPath="$(GamePath)/$(GameData)/Managed/Mono.Posix.dll" />
        <Reference Include="Mono.WebBrowser" HintPath="$(GamePath)/$(GameData)/Managed/Mono.WebBrowser.dll" />
        <Reference Include="Newtonsoft.Json" HintPath="$(GamePath)/$(GameData)/Managed/Newtonsoft.Json.dll" />
        <Reference Include="Novell.Directory.Ldap" HintPath="$(GamePath)/$(GameData)/Managed/Novell.Directory.Ldap.dll" />
        <Reference Include="Ookii.Dialogs" HintPath="$(GamePath)/$(GameData)/Managed/Ookii.Dialogs.dll" />
        <Reference Include="Purchasing.Common" HintPath="$(GamePath)/$(GameData)/Managed/Purchasing.Common.dll" />
        <Reference Include="RDTools" HintPath="$(GamePath)/$(GameData)/Managed/RDTools.dll" />
        <Reference Include="Rewired_Core" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Core.dll" />
        <Reference Include="Rewired_Windows" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Windows.dll" />
        <Reference Include="Rewired_Windows_Functions" HintPath="$(GamePath)/$(GameData)/Managed/Rewired_Windows_Functions.dll" />
        <Reference Include="Unity.Addressables" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Addressables.dll" />
        <Reference Include="Unity.Burst" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Burst.dll" />
        <Reference Include="Unity.Burst.Unsafe" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Burst.Unsafe.dll" />
        <Reference Include="Unity.Collections" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Collections.dll" />
        <Reference Include="Unity.Collections.LowLevel.ILSupport" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Collections.LowLevel.ILSupport.dll" />
        <Reference Include="Unity.Mathematics" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Mathematics.dll" />
        <Reference Include="Unity.MemoryProfiler" HintPath="$(GamePath)/$(GameData)/Managed/Unity.MemoryProfiler.dll" />
        <Reference Include="Unity.Profiling.Core" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Profiling.Core.dll" />
        <Reference Include="Unity.ResourceManager" HintPath="$(GamePath)/$(GameData)/Managed/Unity.ResourceManager.dll" />
        <Reference Include="Unity.ScriptableBuildPipeline" HintPath="$(GamePath)/$(GameData)/Managed/Unity.ScriptableBuildPipeline.dll" />
        <Reference Include="Unity.Services.Core" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.dll" />
        <Reference Include="Unity.Services.Core.Analytics" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Analytics.dll" />
        <Reference Include="Unity.Services.Core.Components" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Components.dll" />
        <Reference Include="Unity.Services.Core.Configuration" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Configuration.dll" />
        <Reference Include="Unity.Services.Core.Device" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Device.dll" />
        <Reference Include="Unity.Services.Core.Environments" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Environments.dll" />
        <Reference Include="Unity.Services.Core.Environments.Internal" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Environments.Internal.dll" />
        <Reference Include="Unity.Services.Core.Internal" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Internal.dll" />
        <Reference Include="Unity.Services.Core.Networking" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Networking.dll" />
        <Reference Include="Unity.Services.Core.Registration" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Registration.dll" />
        <Reference Include="Unity.Services.Core.Scheduler" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Scheduler.dll" />
        <Reference Include="Unity.Services.Core.Telemetry" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Telemetry.dll" />
        <Reference Include="Unity.Services.Core.Threading" HintPath="$(GamePath)/$(GameData)/Managed/Unity.Services.Core.Threading.dll" />
        <Reference Include="Unity.TextMeshPro" HintPath="$(GamePath)/$(GameData)/Managed/Unity.TextMeshPro.dll" />
        <Reference Include="UnityEngine" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.dll" />
        <Reference Include="UnityEngine.AccessibilityModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AccessibilityModule.dll" />
        <Reference Include="UnityEngine.AIModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AIModule.dll" />
        <Reference Include="UnityEngine.AndroidJNIModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AndroidJNIModule.dll" />
        <Reference Include="UnityEngine.AnimationModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AnimationModule.dll" />
        <Reference Include="UnityEngine.ARModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ARModule.dll" />
        <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AssetBundleModule.dll" />
        <Reference Include="UnityEngine.AudioModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.AudioModule.dll" />
        <Reference Include="UnityEngine.ClothModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ClothModule.dll" />
        <Reference Include="UnityEngine.ClusterInputModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ClusterInputModule.dll" />
        <Reference Include="UnityEngine.ClusterRendererModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ClusterRendererModule.dll" />
        <Reference Include="UnityEngine.ContentLoadModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ContentLoadModule.dll" />
        <Reference Include="UnityEngine.CoreModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.CoreModule.dll" />
        <Reference Include="UnityEngine.CrashReportingModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.CrashReportingModule.dll" />
        <Reference Include="UnityEngine.DirectorModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.DirectorModule.dll" />
        <Reference Include="UnityEngine.DSPGraphModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.DSPGraphModule.dll" />
        <Reference Include="UnityEngine.GameCenterModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.GameCenterModule.dll" />
        <Reference Include="UnityEngine.GIModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.GIModule.dll" />
        <Reference Include="UnityEngine.GridModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.GridModule.dll" />
        <Reference Include="UnityEngine.HotReloadModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.HotReloadModule.dll" />
        <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ImageConversionModule.dll" />
        <Reference Include="UnityEngine.IMGUIModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.IMGUIModule.dll" />
        <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.InputLegacyModule.dll" />
        <Reference Include="UnityEngine.InputModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.InputModule.dll" />
        <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.JSONSerializeModule.dll" />
        <Reference Include="UnityEngine.LocalizationModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.LocalizationModule.dll" />
        <Reference Include="UnityEngine.NVIDIAModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.NVIDIAModule.dll" />
        <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ParticleSystemModule.dll" />
        <Reference Include="UnityEngine.PerformanceReportingModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.PerformanceReportingModule.dll" />
        <Reference Include="UnityEngine.Physics2DModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Physics2DModule.dll" />
        <Reference Include="UnityEngine.PhysicsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.PhysicsModule.dll" />
        <Reference Include="UnityEngine.ProfilerModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ProfilerModule.dll" />
        <Reference Include="UnityEngine.PropertiesModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.PropertiesModule.dll" />
        <Reference Include="UnityEngine.Purchasing" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleCore" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.AppleCore.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleMacosStub" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.AppleMacosStub.dll" />
        <Reference Include="UnityEngine.Purchasing.AppleStub" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.AppleStub.dll" />
        <Reference Include="UnityEngine.Purchasing.Codeless" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.Codeless.dll" />
        <Reference Include="UnityEngine.Purchasing.SecurityCore" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.SecurityCore.dll" />
        <Reference Include="UnityEngine.Purchasing.SecurityStub" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.SecurityStub.dll" />
        <Reference Include="UnityEngine.Purchasing.Stores" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.Stores.dll" />
        <Reference Include="UnityEngine.Purchasing.WinRTCore" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.WinRTCore.dll" />
        <Reference Include="UnityEngine.Purchasing.WinRTStub" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.Purchasing.WinRTStub.dll" />
        <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll" />
        <Reference Include="UnityEngine.ScreenCaptureModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.ScreenCaptureModule.dll" />
        <Reference Include="UnityEngine.SharedInternalsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.SharedInternalsModule.dll" />
        <Reference Include="UnityEngine.SpriteMaskModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.SpriteMaskModule.dll" />
        <Reference Include="UnityEngine.SpriteShapeModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.SpriteShapeModule.dll" />
        <Reference Include="UnityEngine.StreamingModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.StreamingModule.dll" />
        <Reference Include="UnityEngine.SubstanceModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.SubstanceModule.dll" />
        <Reference Include="UnityEngine.SubsystemsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.SubsystemsModule.dll" />
        <Reference Include="UnityEngine.TerrainModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TerrainModule.dll" />
        <Reference Include="UnityEngine.TerrainPhysicsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TerrainPhysicsModule.dll" />
        <Reference Include="UnityEngine.TextCoreFontEngineModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TextCoreFontEngineModule.dll" />
        <Reference Include="UnityEngine.TextCoreTextEngineModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TextCoreTextEngineModule.dll" />
        <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TextRenderingModule.dll" />
        <Reference Include="UnityEngine.TilemapModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TilemapModule.dll" />
        <Reference Include="UnityEngine.TLSModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.TLSModule.dll" />
        <Reference Include="UnityEngine.UI" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UI.dll" />
        <Reference Include="UnityEngine.UIElementsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UIElementsModule.dll" />
        <Reference Include="UnityEngine.UIModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UIModule.dll" />
        <Reference Include="UnityEngine.UmbraModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UmbraModule.dll" />
        <Reference Include="UnityEngine.UnityAnalyticsCommonModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityAnalyticsCommonModule.dll" />
        <Reference Include="UnityEngine.UnityAnalyticsModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityAnalyticsModule.dll" />
        <Reference Include="UnityEngine.UnityConnectModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityConnectModule.dll" />
        <Reference Include="UnityEngine.UnityCurlModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityCurlModule.dll" />
        <Reference Include="UnityEngine.UnityTestProtocolModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityTestProtocolModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestAudioModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityWebRequestAudioModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityWebRequestModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestTextureModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityWebRequestTextureModule.dll" />
        <Reference Include="UnityEngine.UnityWebRequestWWWModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.UnityWebRequestWWWModule.dll" />
        <Reference Include="UnityEngine.VehiclesModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.VehiclesModule.dll" />
        <Reference Include="UnityEngine.VFXModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.VFXModule.dll" />
        <Reference Include="UnityEngine.VideoModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.VideoModule.dll" />
        <Reference Include="UnityEngine.VirtualTexturingModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.VirtualTexturingModule.dll" />
        <Reference Include="UnityEngine.VRModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.VRModule.dll" />
        <Reference Include="UnityEngine.WindModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.WindModule.dll" />
        <Reference Include="UnityEngine.XRModule" HintPath="$(GamePath)/$(GameData)/Managed/UnityEngine.XRModule.dll" />
    </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resource\Embedded\**\*" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="Build" Condition="'$(SkipPostBuild)' != 'true'">
        <MakeDir Directories="$(GamePath)/UserLibs" Condition="'$(TargetPath)' != ''" />
        <Copy Condition="'$(TargetPath)' != ''" SourceFiles="$(TargetPath)" DestinationFolder="$(GamePath)/UserLibs" SkipUnchangedFiles="true" />

		<ItemGroup>
			<ExportFiles Include="Resource/Export/**/*.*" />
		</ItemGroup>

		<MakeDir Directories="$(GamePath)/UserData/Overlayer/Module/ADOFAI/" />
		<Copy SourceFiles="@(ExportFiles)" DestinationFiles="@(ExportFiles->'$(GamePath)/UserData/Overlayer/Module/ADOFAI/%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />

        <PropertyGroup>
            <SolutionRoot Condition="'$(SolutionDir)' != ''">$(SolutionDir)</SolutionRoot>
            <SolutionRoot Condition="'$(SolutionDir)' == ''">$(MSBuildProjectDirectory)\..\</SolutionRoot>
            <BuildOutputDir>$(SolutionRoot)\.build\$(Configuration)\$(TargetName)</BuildOutputDir>
        </PropertyGroup>
        <MakeDir Directories="$(BuildOutputDir)\UserLibs" Condition="'$(TargetPath)' != ''" />
        <Copy Condition="'$(TargetPath)' != ''" SourceFiles="$(TargetPath)" DestinationFolder="$(BuildOutputDir)\UserLibs" SkipUnchangedFiles="true" />
        <MakeDir Directories="$(BuildOutputDir)\UserData\Overlayer\Module\ADOFAI" />
        <Copy SourceFiles="@(ExportFiles)" DestinationFiles="@(ExportFiles->'$(BuildOutputDir)\UserData\Overlayer\Module\ADOFAI\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    </Target>
</Project>
